"""add student personal details fields

Revision ID: b8c087fcbc26
Revises: 558997ca8705
Create Date: 2026-09-22 15:24:46.054841

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8c087fcbc26"
down_revision: str | Sequence[str] | None = "558997ca8705"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student", sa.Column("date_of_birth", sa.Date(), nullable=True))
    op.add_column(
        "student",
        sa.Column(
            "place_of_birth",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column("student", sa.Column("date_of_baptism", sa.Date(), nullable=True))
    op.add_column(
        "student",
        sa.Column(
            "place_of_baptism",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "student", sa.Column("date_of_first_communion", sa.Date(), nullable=True)
    )
    op.add_column(
        "student",
        sa.Column(
            "place_of_first_communion",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "student", sa.Column("date_of_confirmation", sa.Date(), nullable=True)
    )
    op.add_column(
        "student",
        sa.Column(
            "place_of_confirmation",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "student",
        sa.Column(
            "father_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        "student",
        sa.Column(
            "father_phone_number",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "student",
        sa.Column(
            "mother_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        "student",
        sa.Column(
            "mother_phone_number",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "student",
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student", "address")
    op.drop_column("student", "mother_phone_number")
    op.drop_column("student", "mother_name")
    op.drop_column("student", "father_phone_number")
    op.drop_column("student", "father_name")
    op.drop_column("student", "place_of_confirmation")
    op.drop_column("student", "date_of_confirmation")
    op.drop_column("student", "place_of_first_communion")
    op.drop_column("student", "date_of_first_communion")
    op.drop_column("student", "place_of_baptism")
    op.drop_column("student", "date_of_baptism")
    op.drop_column("student", "place_of_birth")
    op.drop_column("student", "date_of_birth")
    # ### end Alembic commands ###
